### PR TITLE
fix(subplanners): Match aliased dependencies by name and semver

### LINKED ISSUE #345: Bug: BUILD file for serenity=0.10.2 is incorrectly generated
When generating a BUILD files for serenity=0.10.2, the following `rust_library` rule is generated:
```
rust_library(
    name = "serenity",
    srcs = glob(["**/*.rs"]),
    aliases = {
        "@raze__async_tungstenite__0_11_0//:async_tungstenite": "async_tungstenite_compat",
        "@raze__bytes__1_0_1//:bytes": "bytes_compat",
        "@raze__reqwest__0_11_0//:reqwest": "reqwest_compat",
        "@raze__tokio__1_0_2//:tokio": "tokio_compat",
    },
    crate_features = [
        "async-tungstenite",
        "base64",
        "builder",
        "bytes",
        "cache",
        "client",
        "command_attr",
        "default",
        "default_no_backend",
        "flate2",
        "framework",
        "gateway",
        "http",
        "model",
        "reqwest",
        "rustls_backend",
        "rustls_backend_marker",
        "standard_framework",
        "static_assertions",
        "tokio",
        "typemap_rev",
        "url",
        "utils",
        "uwl",
    ],
    crate_root = "src/lib.rs",
    crate_type = "lib",
    data = [],
    edition = "2018",
    proc_macro_deps = [
        "@raze__async_trait__0_1_42//:async_trait",
        "@raze__command_attr__0_3_3//:command_attr",
    ],
    rustc_flags = [
        "--cap-lints=allow",
    ],
    tags = [
        "cargo-raze",
        "manual",
    ],
    version = "0.10.2",
    # buildifier: leave-alone
    deps = [
        ":serenity_build_script",
        "@raze__async_tungstenite__0_11_0//:async_tungstenite",
        "@raze__base64__0_13_0//:base64",
        "@raze__bitflags__1_2_1//:bitflags",
        "@raze__bytes__1_0_1//:bytes",
        "@raze__chrono__0_4_19//:chrono",
        "@raze__flate2__1_0_19//:flate2",
        "@raze__futures__0_3_11//:futures",
        "@raze__percent_encoding__2_1_0//:percent_encoding",
        "@raze__reqwest__0_11_0//:reqwest",
        "@raze__serde__1_0_119//:serde",
        "@raze__serde_json__1_0_61//:serde_json",
        "@raze__static_assertions__1_1_0//:static_assertions",
        "@raze__tokio__1_0_2//:tokio",
        "@raze__tracing__0_1_22//:tracing",
        "@raze__tracing_futures__0_2_4//:tracing_futures",
        "@raze__typemap_rev__0_1_4//:typemap_rev",
        "@raze__url__2_2_0//:url",
        "@raze__uwl__0_6_0//:uwl",
    ],
)
```

The main point of issue is that the aliases are all suffixed with "_compat", which is not supposed to happen. When Bazel attempts to build the crate, many errors are produced that look like:
```
error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
   --> external/raze__serenity__0_10_2/src/client/dispatch.rs:701:13
    |
701 |             tokio::spawn(async move {
    |             ^^^^^ use of undeclared crate or module `tokio`

```
When the BUILD file is manually edited to have
```
aliases = {
        "@raze__async_tungstenite__0_11_0//:async_tungstenite": "async_tungstenite",
        "@raze__bytes__1_0_1//:bytes": "bytes",
        "@raze__reqwest__0_11_0//:reqwest": "reqwest",
        "@raze__tokio__1_0_2//:tokio": "tokio",
    },
```
instead, the crate builds just fine. Any reason why "_compat" might be getting appended?

### PR DESCRIPTION
**Pull request by Arm1stice**
This PR adds an additional check to ensure that a dependency with an alias is matched by both name and it's version compared to the required semver in the dependency metadata. This allows a situation in which a crate has a dependency listed multiple times with different versions, some with aliases and others without.

Fixes #345

### CODE REVIEW

**Comment by Arm1stice** [comment]
@googlebot I signed it!

Must have triggered since I'm not currently an employee :sweat_smile:

**Comment by UebelAndre** [comment]
Hey! Glad to see you're around and still making contributions. Do you think you can find a smaller crate that demonstrates this behavior? I was the author of these template files and before I started on https://github.com/google/cargo-raze/pull/300 I was only dealing with small sets of metadata until I ran into `test_plan_build_produces_aliased_dependencies`. Would you also be willing to also update that test to use a smaller example and maybe add some comments kinda explaining what's going on in that test?

**Comment by Arm1stice** [comment]
@UebelAndre Tests should be fixed now, let me know if you think there is more room for improvement

**Comment by UebelAndre** [comment]
> @UebelAndre Tests should be fixed now, let me know if you think there is more room for improvement

This looks **MUCH** better, thank you so much!!!  

@GregBowyer started working on a way to fix various aliasing bugs in https://github.com/google/cargo-raze/pull/282 so they might be interested in this as well. Other than that, @acmcarther will have to also review this before it's merged.

But again, thank you! Very excited to finally understand what that test does and I think [cargo-raze-alias-test](https://crates.io/crates/cargo-raze-alias-test) is pretty awesome 😄

**Review by acmcarther — APPROVED** [review]
LGTM

**Comment by UebelAndre** [comment]
@Arm1stice can you link the source code to `cargo-raze-alias-test` here? I think we should add it to this repo so we can expand upon it for various aliasing examples.

**Comment by UebelAndre** [comment]
re https://github.com/google/cargo-raze/pull/346#issuecomment-769206679 
@Arm1stice Hey, just pinging this again 😅

**Comment by Arm1stice** [comment]
> re [#346 (comment)](https://github.com/google/cargo-raze/pull/346#issuecomment-769206679)
> @Arm1stice Hey, just pinging this again 😅

Sorry, missed this. I have published at https://github.com/Arm1stice/cargo-raze-alias-test

**Pull request merged**
