### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by acmcarther**
This repo was migrated to buildkite ages ago, and Travis hasn't been functional for some time.

### CODE REVIEW

**Review by UebelAndre — APPROVED** [review]
Thanks!

**Comment by UebelAndre** [comment]
If you're in the cleanup mood, do you also want to delete some old branches? 😅

**Comment by acmcarther** [comment]
> If you're in the cleanup mood, do you also want to delete some old branches?

Done.

**Comment by acmcarther** [comment]
Thanks for your quick review!

**Comment by UebelAndre** [comment]
> Thanks for your quick review!

No problem, thanks for stopping by for this PR. Good to "see" you again 😄

**Pull request merged**
