### PR TITLE
Fixed dev dependency aliases

### PR DESCRIPTION
**Pull request by UebelAndre**
This fixes a regression brought up in #355

### CODE REVIEW

**Comment by UebelAndre** [comment]
@dfreese @acmcarther do you have a moment to review this and potentially do a patch release?

**Review by dfreese — APPROVED** [review]

**Comment by dfreese** [comment]
To the point brought up in #355, having the examples technically catches this, but it would be preferable if this was covered by a unit test some how.

**Comment by UebelAndre** [comment]
> To the point brought up in #355, having the examples technically catches this, but it would be preferable if this was covered by a unit test some how.

Agreed. I've been meaning to do some slight refactoring as part of https://github.com/google/cargo-raze/issues/339 which I believe will require similar testing. When I have some free time I'll try to do this.

**Comment by UebelAndre** [comment]
@acmcarther @dfreese Can either of you do a release to actually resolve #355 ? 🙏

**Pull request merged**
