### PR TITLE
platform-specific aliases were missing

### LINKED ISSUE #242: reqwests fails to compile with git HEAD
Carrying on from https://github.com/google/cargo-raze/pull/212#issuecomment-705507497

To reproduce, checkout https://github.com/ankitects/cargo-raze-bug-examples, checkout HEAD^, and run repro.sh. Tested on a Mac.

### PR DESCRIPTION
**Pull request by dae**
Closes #242

### CODE REVIEW

**Comment by acmcarther** [comment]
Travis says this is not producing Buildifier compliant BUILD files. I'm not totally clear why... perhaps it's causing
```
aliases = {
}
```

to be generated in some cases? Running ./smoke-test.sh and inspecting `examples/vendored/complicated_cargo_library/cargo/vendor/MacTypes-sys-2.1.0/BUILD.bazel` might be illuminating.

**Comment by dae** [comment]
I wasn't able to remove aliases in all cases - suggestions welcome: https://github.com/google/cargo-raze/pull/244/commits/91c3999000dbc071ac224e2407fd0f82cc4685ba

**Comment by UebelAndre** [comment]
I think it's fine to have aliases there so long as there's no impact on behavior or new buildifier defects being generated. I feel the templates are a bit hairy and should be streamlined. Maybe you could write a unit test that checks for some particular output so cleaning up the rendering logic would be safer to do in the future? It's up to @acmcarther though. Otherwise LGTM.

**Comment by acmcarther** [comment]
Yeah, adding empty aliases SGTM.

LGTM. Thanks again!

**Pull request merged**
