### PR TITLE
Testing bazel-based build breakage with upstream rules_rust

### PR DESCRIPTION
**Pull request by dfreese**

### CODE REVIEW

**Comment by dfreese** [comment]
@UebelAndre, in attempting to track down some of the errors in #482, it looks like cargo no longer gets pulled in automatically after bumping the version of rules_rust.  I'm assuming that was an intentional change upstream.  Before I splunk too much further, is the appropriate fix on that obvious to you?

**Comment by dfreese** [comment]
Looks like the breaking change was https://github.com/bazelbuild/rules_rust/pull/1079, which flipped incompatible_disable_custom_test_launcher.

**Comment by UebelAndre** [comment]
I'm so sorry, I don't know how I missed this issue! I think all that's needed is for the tests to explicitly handle making the `CARGO` and `RUSTC` environment variables absolute paths. Then I think all should be fine.

**Comment by dfreese** [comment]
fixed with #506, Thanks @sayrer

**Pull request closed without merging**
