### PR TITLE
Pull @rules_rust in cargo_raze_repositories().

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
cc @UebelAndre

**Review by UebelAndre — APPROVED** [review]
Nice! Thanks for fixing that 😀

**Comment by UebelAndre** [comment]
Oh, actually, I'm not sure if the call to `rust_repositories` should be in that file. Users may not want to call that and instead setup toolchains themselves using `rust_repository_set` directly or something.

**Comment by PiotrSikora** [comment]
> Oh, actually, I'm not sure if the call to `rust_repositories` should be in that file. Users may not want to call that and instead setup toolchains themselves using `rust_repository_set` directly or something.

`rules_repositories()` configures a few default `rust_repository_set()`, but it doesn't prevent people from adding more on their own, so I don't believe it breaks any real use cases.

**Comment by UebelAndre** [comment]
That sounds right to me. Then I think this change is good. Thanks again!

**Comment by acmcarther** [comment]
LGTM

**Pull request merged**
