### PR TITLE
Updated windows platforms from `gnu` to `msvc`

### PR DESCRIPTION
**Pull request by UebelAndre**
Not trying to steal the thunder from @dae but there is currently an incompatibility between `cargo-raze` and head of `rules_rust` This PR is the same change as #245 but with updated smoke-tests (the only thing broken about the PR). I'd love to see this get merged (or #245 get updated and merged) and then a release be made.

### CODE REVIEW

**Comment by acmcarther** [comment]
I would prefer to submit @dae's PR, but I don't feel strongly about this, particularly if we're fixing an important breakage. I'll check in on both of these in a couple of hours and submit this one if there isn't forward movement.

**Comment by UebelAndre** [comment]
I would prefer to have that PR merged as well, the fix is quite small but yeah, I don't know when he'll be around next. There was a breakage in `rules_rust` that was fixed by regenerating some dependencies using these changes and I feel it's important to get this fix out in a timely manner to ensure the rules and this tool are compatible with each other.

Definitely your call to make @acmcarther

**Comment by dae** [comment]
Sorry for the delay, I've pushed Uebel's change into my branch as well. Please feel free to merge either - fixing the breaking build is more important than credit for a few character change. :-)

**Comment by UebelAndre** [comment]
@acmcarther #245 is ready to merge. Closing this ticket as a duplicate

**Pull request closed without merging**
