### PR TITLE
Experimental API: Added a `render_package_aliases` setting

### PR DESCRIPTION
**Pull request by UebelAndre**
`render_package_aliases` can be used to prevent aliases from being rendered into the `BUILD` file in normal output by setting this field to `false`. It currently defaults to `true`. This can be used to prevent unnecessary targets from being generated in a workspace since `crate_deps` and `all_crate_deps` can be used in their stead.

```command
cargo_workspace % bazel query ...
```
```output
//remote/cargo_workspace/rng/cargo:rand
//remote/cargo_workspace/printer/cargo:ferris_says
//remote/cargo_workspace/num_printer/cargo:clap
//remote/cargo_workspace/num_printer:number_printer
//remote/cargo_workspace/printer:printer
//remote/cargo_workspace/rng:rng
```

becomes

```command
cargo_workspace % bazel query ...
```
```output
cargo_workspace % bazel query ...
//remote/cargo_workspace/num_printer:number_printer
//remote/cargo_workspace/printer:printer
//remote/cargo_workspace/rng:rng
```

### CODE REVIEW

**Comment by UebelAndre** [comment]
Oh no! I accidentally rebased this branch! Sorry about that 😅 I know it messes up reviews so won't do that again.

**Comment by UebelAndre** [comment]
@acmcarther FYI this is the final PR before opening a PR for the Bazel conversion I've been working on.

**Comment by UebelAndre** [comment]
@acmcarther  FYI: Gonna rebase to fix the merge conflicts

**Comment by UebelAndre** [comment]
@acmcarther Rebased and ready for review

**Review by acmcarther — APPROVED** [review]
The aliases are intended to prevent workspace BUILD rules from accessing transitive dependencies. This only exists to avoid having people shoot themselves in the foot.

I don't feel strongly enough about this to prevent this PR from going in, but that was the original purpose.

**Comment by UebelAndre** [comment]
Yeah, That makes sense to me. This is purely something to go with the experimental API where the aliases aren't used. So this cleans up the output and I find makes the experience with multi toml / cargo workspaces much clearer

**Pull request merged**
