### PR TITLE
Workspace support examples

### PR DESCRIPTION
**Pull request by UebelAndre**
This is a followup of https://github.com/google/cargo-raze/pull/276 which adds examples demonstrating the use of cargo workspaces. Only the final two commits in this PR are relevant. Please see https://github.com/google/cargo-raze/pull/276 for details about anything before that.

### CODE REVIEW

**Comment by UebelAndre** [comment]
@acmcarther Following #276 being merged, I've rebased this and is also ready for review.

**Comment by acmcarther** [comment]
This PR looks good to me. Are you planning to prepare an update to the README as well? That's probably more accessible to users than this set of examples.

**Comment by UebelAndre** [comment]
I can update the README in https://github.com/google/cargo-raze/pull/302 which is a change that greatly improves the usability of cargo workspace support. Does that sound good?

**Comment by acmcarther** [comment]
That sounds fine.

**Pull request merged**
