### PR TITLE
Moved components of the `planning` module into a directory

### PR DESCRIPTION
**Pull request by UebelAndre**
This is the next commit after #255

### CODE REVIEW

**Comment by UebelAndre** [comment]
@acmcarther the diff here will get smaller once #255 is merged.

**Comment by acmcarther** [comment]
I'm not really convinced that moving license into planning enhances clarity, but I don't feel strongly about it.

LGTM.

**Review by acmcarther — APPROVED** [review]

**Comment by acmcarther** [comment]
I guess this can just be merged without being synced, so I'll do that.

**Comment by UebelAndre** [comment]
`planning` is the only module that uses `license` so I thought that's where it should go. If this doesn't make sense lets move it. But this is the first change in a larger change I want to make

**Pull request merged**
