### PR TITLE
Improved tera errors

### PR DESCRIPTION
**Pull request by UebelAndre**
This fixes some annoyingly vague errors:
```output
Error: Raze failed to render with cause: "Failed to render 'templates/remote_crates.bzl.template'
```
becomes
```output
Error: Raze failed to render with cause: "Failed to render 'templates/remote_crates.bzl.template'
└─Template 'templates/partials/remote_crates_patch.template' not found"
```

### CODE REVIEW

**Comment by UebelAndre** [comment]
@damienmg Hey, can I get your eyes on this? It's small (and I promise not to add anything to it 😅)

**Comment by damienmg** [comment]
What is the relation between the 3 commits? Shouldn't that be 3 different PRs?

**Comment by UebelAndre** [comment]
These are all things that I split out of #212 to try and make that more focused. I can split these commits up into different PRs if you prefer.

**Comment by damienmg** [comment]
Sorry I realized I haven't answered. We squash all PR into a single commit so they make more sense as separate PR. It is a general approach at Google (and people using Gerrit) to do a code review per logical change (for this PR 1 change = 1 commit) and we tend to reflect this in our projects on github.

Do you mind splitting this into 3 PRs?

**Comment by UebelAndre** [comment]
@damienmg Sounds good and makes sense.

Done 😄 
#213 #214

**Comment by damienmg** [comment]
Thanks!

**Pull request merged**
