### PR TITLE
Disable windows build in Buildkite, and update badge

### PR DESCRIPTION
**Pull request by acmcarther**
Windows is broken for a somewhat inconsequential reason:

TL;DR: It can't execute the repository rule for `cargo_raze_examples`. I think this can be skipped in windows if necessary.

```
$ bazel --output_user_root=C:/b --nomaster_bazelrc --bazelrc=/dev/null info
--
  | INFO: SHA256 (https://static.rust-lang.org/dist/cargo-1.49.0-x86_64-pc-windows-msvc.tar.gz) = 84b44835a3f275fef70cd86a527d086c537e59fb3209fe8bbef1eeb1da6edbb6
  | INFO: Repository cargo_raze_examples instantiated at:
  | C:/b/bk-windows-r4v8/bazel/cargo-raze/WORKSPACE.bazel:32:20: in <toplevel>
  | C:/b/bk-windows-r4v8/bazel/cargo-raze/tools/examples_repository.bzl:108:25: in examples_repository
  | Repository rule _examples_repository defined at:
  | C:/b/bk-windows-r4v8/bazel/cargo-raze/tools/examples_repository.bzl:82:39: in <toplevel>
  | ERROR: An error occurred during the fetch of repository 'cargo_raze_examples':
  | Traceback (most recent call last):
  | File "C:/b/bk-windows-r4v8/bazel/cargo-raze/tools/examples_repository.bzl", line 76, column 13, in _examples_repository_impl
  | fail(EXECUTE_FAIL_MESSAGE.format(
  | Error in fail: Failed to setup examples repository with exit code (256).
  | --------stdout:
  |  
  | --------stderr:
  | java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\b\bk-windows-r4v8\bazel\cargo-raze\tools\examples_repository_tools.sh" vendor): %1 is not a valid Win32 application.
  | (error: 193)
  | ERROR: Error fetching repository: Traceback (most recent call last):
  | File "C:/b/bk-windows-r4v8/bazel/cargo-raze/tools/examples_repository.bzl", line 76, column 13, in _examples_repository_impl
  | fail(EXECUTE_FAIL_MESSAGE.format(
  | Error in fail: Failed to setup examples repository with exit code (256).
  | --------stdout:
  |  
  | --------stderr:
  | java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\b\bk-windows-r4v8\bazel\cargo-raze\tools\examples_repository_tools.sh" vendor): %1 is not a valid Win32 application.
  | (error: 193)
  | ERROR: no such package '@cargo_raze_examples//': Failed to setup examples repository with exit code (256).
  | --------stdout:

```

### CODE REVIEW

**Comment by acmcarther** [comment]
(OSX and Ubuntu are green, btw)

**Comment by UebelAndre** [comment]
I'm still met with a login page for cargo-raze 😞 But Glad to see it turns green! 😄

**Comment by UebelAndre** [comment]
https://github.com/google/cargo-raze/pull/375 is the only additional thing that should be added for BazelCI but additionally https://github.com/google/cargo-raze/pull/374 and https://github.com/google/cargo-raze/pull/365 would pave the way for getting everything correctly setup and successfully building.

**Comment by acmcarther** [comment]
Yeah, it seems that it's set to private and I don't have (or can't find) the knobs to make it public.

**Comment by UebelAndre** [comment]
Also, great to see you again and I hope your RL sutff  is going better now! 😄

**Pull request merged**
