### PR TITLE
Sort fields inside generated targets to match buildifier.

### LINKED ISSUE #192: Generated BUILD files are not properly formatted.
Generated `BUILD` files are not properly formatted per [buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier).

```
$ buildifier -lint=fix cargo/BUILD
$ git diff cargo/BUILD
```
```
diff --git a/cargo/BUILD b/cargo/BUILD
index a8639e5..832c24e 100644
--- a/cargo/BUILD
+++ b/cargo/BUILD
@@ -3,26 +3,31 @@ cargo-raze workspace build file.
 
 DO NOT EDIT! Replaced on runs of cargo-raze
 """
+
 package(default_visibility = ["//visibility:public"])
 
 licenses([
-  "notice" # See individual crates for specific licenses
+    "notice",  # See individual crates for specific licenses
 ])
+
 alias(
     name = "chrono",
     actual = "@raze__chrono__0_4_13//:chrono",
     tags = ["cargo-raze"],
 )
+
 alias(
     name = "hashbrown",
     actual = "@raze__hashbrown__0_7_2//:hashbrown",
     tags = ["cargo-raze"],
 )
+
 alias(
     name = "log",
     actual = "@raze__log__0_4_11//:log",
     tags = ["cargo-raze"],
 )
+
 alias(
     name = "wee_alloc",
     actual = "@raze__wee_alloc__0_4_5//:wee_alloc",
```
```
$ buildifier -lint=fix cargo/remote/log-0.4.11.BUILD
$ git diff cargo/remote/log-0.4.11.BUILD
```
```
diff --git a/cargo/remote/log-0.4.11.BUILD b/cargo/remote/log-0.4.11.BUILD
index ec0b13c..5ed228c 100644
--- a/cargo/remote/log-0.4.11.BUILD
+++ b/cargo/remote/log-0.4.11.BUILD
@@ -3,45 +3,43 @@ cargo-raze crate build file.
 
 DO NOT EDIT! Replaced on runs of cargo-raze
 """
-package(default_visibility = [
-  # Public for visibility by "@raze__crate__version//" targets.
-  #
-  # Prefer access through "//cargo", which limits external
-  # visibility to explicit Cargo.toml dependencies.
-  "//visibility:public",
-])
-
-licenses([
-  "notice", # MIT from expression "MIT OR Apache-2.0"
-])
 
 load(
     "@io_bazel_rules_rust//rust:rust.bzl",
     "rust_library",
-    "rust_binary",
-    "rust_test",
 )
 
+package(default_visibility = [
+    # Public for visibility by "@raze__crate__version//" targets.
+    #
+    # Prefer access through "//cargo", which limits external
+    # visibility to explicit Cargo.toml dependencies.
+    "//visibility:public",
+])
+
+licenses([
+    "notice",  # MIT from expression "MIT OR Apache-2.0"
+])
 
 # Unsupported target "build-script-build" with type "custom-build" omitted
 # Unsupported target "filters" with type "test" omitted
 
 rust_library(
     name = "log",
-    crate_type = "lib",
-    deps = [
-        "@raze__cfg_if__0_1_10//:cfg_if",
-    ],
     srcs = glob(["**/*.rs"]),
+    crate_features = [
+    ],
     crate_root = "src/lib.rs",
+    crate_type = "lib",
     edition = "2015",
     rustc_flags = [
         "--cap-lints=allow",
         "--cfg=atomic_cas",
     ],
-    version = "0.4.11",
     tags = ["cargo-raze"],
-    crate_features = [
+    version = "0.4.11",
+    deps = [
+        "@raze__cfg_if__0_1_10//:cfg_if",
     ],
 )
 
```

### PR DESCRIPTION
**Pull request by PiotrSikora**
Partially fixes #192.

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
This is not currently visible in the CI, because `buildifier` skips those files now (see #260), but there is one outstanding issue found in one of the examples.

It looks that Rust and `buildifier` don't agree on the sorting algorithm:
```
--- a/examples/remote/binary_dependencies/cargo/remote/structopt-derive-0.4.2.BUILD.bazel
+++ b/examples/remote/binary_dependencies/cargo/remote/structopt-derive-0.4.2.BUILD.bazel
@@ -48,8 +48,8 @@ rust_library(
     version = "0.4.2",
     deps = [
         "@remote_binary_dependencies__heck__0_3_1//:heck",
-        "@remote_binary_dependencies__proc_macro_error__0_4_9//:proc_macro_error",
         "@remote_binary_dependencies__proc_macro2__1_0_9//:proc_macro2",
+        "@remote_binary_dependencies__proc_macro_error__0_4_9//:proc_macro_error",
         "@remote_binary_dependencies__quote__1_0_2//:quote",
         "@remote_binary_dependencies__syn__1_0_16//:syn",
     ],
```
and `proc_macro_error` is emitted before `proc_macro2`, whereas `buildifier` expects it after it.

**Comment by PiotrSikora** [comment]
Actually, Rust agrees with the `buildifier`'s order:
```
$ cat test.rs
```
```
fn main() {
  let mut vec = vec![
    "@remote_binary_dependencies__quote__1_0_2//:quote",
    "@remote_binary_dependencies__proc_macro_error__0_4_9//:proc_macro_error",
    "@remote_binary_dependencies__heck__0_3_1//:heck",
    "@remote_binary_dependencies__proc_macro2__1_0_9//:proc_macro2",
    "@remote_binary_dependencies__syn__1_0_16//:syn",
  ];
  vec.sort();
  println!("{:#?}", vec);
}
```
```
$ rustc test.rs -o test && ./test
```
```
[
    "@remote_binary_dependencies__heck__0_3_1//:heck",
    "@remote_binary_dependencies__proc_macro2__1_0_9//:proc_macro2",
    "@remote_binary_dependencies__proc_macro_error__0_4_9//:proc_macro_error",
    "@remote_binary_dependencies__quote__1_0_2//:quote",
    "@remote_binary_dependencies__syn__1_0_16//:syn",
]
```
so the issue is somewhere else in the code. Any ideas, @UebelAndre?

**Comment by UebelAndre** [comment]
@PiotrSikora could I get you to try rebasing these changes on top of #260 

Between you and me we may yet be able to solve this problem! 😄 🙏 🤞

**Comment by UebelAndre** [comment]
> so the issue is somewhere else in the code. Any ideas, @UebelAndre?

I'll do some digging and see what I can come up with sometime tomorrow. For now, can you see what else is generated from rebasing on #260 ?

**Comment by PiotrSikora** [comment]
@UebelAndre Rebased on #260 (on the first commit, not the recent updates, since they are full of conflicting changes with this PR).

That weird sort is literally the only issue (and I'm not sure why it's happening, planner sorts that list via `normal_deps.sort()`).

**Comment by PiotrSikora** [comment]
Changes merged into #260.

**Pull request closed without merging**
