### PR TITLE
Added Code Owners file

### PR DESCRIPTION
**Pull request by UebelAndre**
This PR adds a file which represents users with merging abilities

### CODE REVIEW

**Comment by acmcarther** [comment]
IIUC this file should just be called `CODEOWNERS`, not `CODEOWNERS.md`

I don't see any reference to this [in the relevant docs](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location). Link to your reference?

**Comment by UebelAndre** [comment]
Oh cool, I didn't know about that. I can update this.

**Comment by UebelAndre** [comment]
@acmcarther updated

**Review by acmcarther — APPROVED** [review]
Thanks!

**Pull request merged**
