### PR TITLE
Fix features selection, broken by #478

### PR DESCRIPTION
**Pull request by bsilver8192**
It works properly with no explicit targets set (aka "use all the
targets"), and it also works properly with some of the examples that set
`default-members = []`.

I think there's still something wrong, because it dropped features from
some Windows-specific crates relative to before https://github.com/google/cargo-raze/pull/478, but I'm not sure
what's supposed to happen. At least all the tests in this repository
pass on Linux again...

### CODE REVIEW

**Comment by bsilver8192** [comment]
@sayrer FYI, if you want to take a look.

**Comment by rdelfin** [comment]
I believe this fixes the issue outlined in #530. Thanks a bunch for working on this and fixing it!

**Comment by rdelfin** [comment]
@dfreese is there any chance this change could be included in a patch/minor release? If this fixes the issue, it would be a huge unblocker for our repo

**Comment by PiotrSikora** [comment]
@dfreese @illicitonion @acmcarther could one of you review this and release v0.16.1? `cargo-raze` v0.16.0 is pretty much broken without this fix (see: https://github.com/google/cargo-raze/pull/478#issuecomment-1200362639), and I verified that this PR fixes the issue for me.

**Review by PiotrSikora — APPROVED** [review]

**Comment by illicitonion** [comment]
@sayrer Please could you give this a look?

**Review by dfreese — APPROVED** [review]

**Comment by dfreese** [comment]
published 0.16.1

**Pull request merged**
