### PR TITLE
Sort "tags". 

### PR DESCRIPTION
**Pull request by PiotrSikora**
While there, regenerate examples and third_party.

Missed in #455.

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]

**Comment by illicitonion** [comment]
It looks like this breaks buildifier? I guess maybe tags are meant to be sorted?

**Comment by PiotrSikora** [comment]
@illicitonion great find, thanks for spotting it! I fixed the template and regenerated the artifacts. PTAL.

Perhaps `v0.14.1` is in order, once this is merged in?

**Review by dfreese — APPROVED** [review]
Thanks!

**Comment by dfreese** [comment]
In v0.14.1.

**Pull request merged**
