### PR TITLE
Removed buildifier since it can be ran in BazelCI

### PR DESCRIPTION
**Pull request by UebelAndre**
This should reduce the clutter in the WORKSPACE file

### CODE REVIEW

**Comment by UebelAndre** [comment]
@dfreese Hey, just pinging this one again. I added this for the TravisCI setup but it's no longer necessary and blocking a workflow I'm hoping to be able to use in https://github.com/google/cargo-raze/pull/379 Can I get your eyes on this 🙏

**Comment by UebelAndre** [comment]
@acmcarther @dfreese If either of you are around today, it'd be a huge help to get this merged 🙏

**Comment by UebelAndre** [comment]
@acmcarther Do you have a moment to take a look at this? It removes an unnecessary dependency and improves a Bazel workflow I'm looking to take advantage of (building and running cargo-raze in Bazel)

**Comment by acmcarther** [comment]
Aight I'm here. This LG!

**Pull request merged**
