### PR TITLE
Fix binary dependency aliases

### PR DESCRIPTION
**Pull request by UebelAndre**
This fixes an issue where binary dependencies were having alises rendered for them since they're now artificially considered workspace members.

This can be seen by the removal of [examples/remote/binary_dependencies/texture-synthesis-cli-0.8.0/cargo/BUILD.bazel](https://github.com/google/cargo-raze/pull/312/files#diff-436b544f8665759cb41896b51cd7059908e85acc19ce4ae636ec299b09e46b8e) which is not actually a documented workspace memeber in any `Cargo.toml` file.

### CODE REVIEW

**Comment by UebelAndre** [comment]
@acmcarther small bugfix with some fixed up tests 😄

**Comment by UebelAndre** [comment]
@acmcarther and maybe this would be a good opportunity for other maintainers to do reviews?

@damienmg @dfreese could you guys take a look at this?

**Comment by UebelAndre** [comment]
@acmcarther I also have other small PRs good for undead maintainers. In case you were around today to check this one out.

**Review by acmcarther — APPROVED** [review]

**Comment by UebelAndre** [comment]
Thanks! 🙏

**Pull request merged**
