### PR TITLE
Add support for wasm32-wasi target.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Blocked on https://github.com/bazelbuild/rules_rust/pull/477

**Comment by PiotrSikora** [comment]
@UebelAndre PTAL.

**Review by UebelAndre — APPROVED** [review]
Looks good to me! Thank you so much for adding this!! 🙏

**Comment by UebelAndre** [comment]
@dfreese @acmcarther would either of you be able to take a look as well?

**Review by dfreese — APPROVED** [review]

**Comment by wchargin** [comment]
As a user of `cargo-raze`, is it possible to disable this? This requires
latest `rules_rust`, which also requires Bazel 3.0.0 rather than 0.17.x,
and thus is non-trivial for us to incorporate.

**Comment by UebelAndre** [comment]
What's the specific issue you're running into? You might be able to prevent that target from showing up by giving an explicit list of platform triples to raze via `targets`: 
https://github.com/google/cargo-raze/blob/master/impl/src/settings.rs#L69-L75

**Comment by PiotrSikora** [comment]
@UebelAndre I believe the issue is with bazelbuild/rules_rust#463, not `wasm32-wasi` itself, and anything that requires changes from `rules_rust` after that PR was merged will be an issue for @wchargin.

**Comment by UebelAndre** [comment]
> @UebelAndre I believe the issue is with [bazelbuild/rules_rust#463](https://github.com/bazelbuild/rules_rust/pull/463), not `wasm32-wasi` itself, and anything that requires changes from `rules_rust` after that PR was merged will be an issue for @wchargin.

Ah, that makes more sense. Perhaps a new issue should be opened for this in `rules_rust` linking the relevant issues then?

**Comment by wchargin** [comment]
If I depend on `rand = "0.7.3"` and generate build files with cargo-raze
0.7.0, there’s a dependency edge to `:wasm32-wasi`, which doesn’t exist
at my `rules_rust` version:

```
$ bazel build //third_party/rust:rand
ERROR: While resolving configuration keys for @raze__getrandom__0_1_15//:getrandom: no such target '@io_bazel_rules_rust//rust/platform:wasm32-wasi': target 'wasm32-wasi' not declared in package 'rust/platform' defined by /HOMEDIR/.cache/bazel/_bazel_wchargin/52a95bbdd50941251730eb33b7476a66/external/io_bazel_rules_rust/rust/platform/BUILD
ERROR: Analysis of target '//third_party/rust:rand' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.139s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Setting `targets` on the top-level `raze` settings does seem to fix the
problem; thanks! It doesn’t work if I set it only for the `getrandom`
crate, but I guess it makes sense to define this globally anyway.

(I don’t really see how this is related to the linker API? That’s the
bit that requires Bazel 3.0.0+, yes, but that seems unrelated to me.)

**Comment by UebelAndre** [comment]
> Setting `targets` on the top-level `raze` settings does seem to fix the
> problem; thanks! It doesn’t work if I set it only for the `getrandom`
> crate, but I guess it makes sense to define this globally anyway.

`targets` is a top level setting (or is expected to be) so yeah, you should set it top level like you see in the example I added to my comment above.

> (I don’t really see how this is related to the linker API? That’s the
> bit that requires Bazel 3.0.0+, yes, but that seems unrelated to me.)

I think there was just some confusion around what the core issue was. I do think we `rules_rust` should do something about this though. I'll ping https://github.com/bazelbuild/rules_rust/issues/415 and see if a release can go out to communicate this incompatibility

**Comment by wchargin** [comment]
And thanks to both of you for such quick and helpful responses!

**Comment by PiotrSikora** [comment]
> (I don’t really see how this is related to the linker API? That’s the
> bit that requires Bazel 3.0.0+, yes, but that seems unrelated to me.)

Indeed, the `wasm32-wasi` target requires very recent `rules_rust`, but I don't think it's going to be the only change that does that, which means that the core issue (at least, in my mind) is your inability to update `rules_rust` because of that PR.

**Pull request merged**
